[package]
name = "oxc-zed"
version = "0.3.3"
edition = "2024"
license = "MIT"
publish = true

[lib]
crate-type = ["cdylib"]
path = "src/oxc.rs"

[dependencies]
simple_logger = "5.1.0"
log = "0.4.29"
zed_extension_api = "0.7.0"
