authors = ["Boshen <https://github.com/Boshen>"]
description = "Oxlint and Oxfmt support"
id = "oxc"
name = "Oxc"
repository = "https://github.com/oxc-project/oxc-zed"
schema_version = 1
version = "0.4.2"

[language_servers.oxlint]
code_actions_kind = ["quickfix", "source.fixAll.oxc"]
language = "JavaScript"
languages = [
    "JavaScript",
    "JSX",
    "TypeScript",
    "TSX",
    "Vue.js",
    "Astro",
    "Svelte",
]
name = "Oxlint Language Server"

[language_servers.oxlint.language_ids]
"Astro" = "astro"
"JSX" = "javascriptreact"
"JavaScript" = "javascript"
"Svelte" = "svelte"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js" = "vuejs"

[language_servers.oxfmt]
language = "JavaScript"
languages = [
    "JavaScript",
    "JSX",
    "TypeScript",
    "TSX"
]
name = "Oxfmt Language Server"

[language_servers.oxfmt.language_ids]
"JSX" = "javascriptreact"
"JavaScript" = "javascript"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
